### ISSUE TITLE
Not issues but i appreciate your work

### ISSUE THREAD

**Issue by timotismjntk** [ShinMini/health-care-expoRN#3]
You're my inspiration in react native,
Any plan to do tutorial facerecognition with tensorflow and react native?

**Comment by ShinMini** [comment]
Dear @timotismjntk, thank you for making my day! :)
As you asked, **I do have plans** to create a tutorial on using **TensorFlow** and **React Native** with **TypeScript**.

This tutorial might include an AI model built with TensorFlow, and I'll handle the data using JSON format in React Native storage libraries (e.g., Redux, local storage, etc.).

**However**, I am currently working on my company's project until around **July**. Once I am available, I will let you know.

I look forward to sharing the tutorial with you. Best regards, @ShinMini

**Comment by timotismjntk** [comment]
Thank you
